### ISSUE TITLE
I think your SSL certificate is expired.

### ISSUE THREAD

**Issue by glennabaron** [acburdine/acburdine.me#4]
Or something.

<img width="1440" alt="screen shot 2018-03-30 at 4 06 27 pm" src="https://user-images.githubusercontent.com/4306882/38152182-83d1f3fa-3434-11e8-9c19-f5df94c4fc6e.png">

**Comment by acburdine** [comment]
Haha yeah, I’ve known about that for a while. Has to do with how I (incorrectly) set up Cloudflare. Been meaning to move this site to Netlify for a while which should fix the issue, but, you know, priorities....

**Comment by acburdine** [comment]
Seriously needs a rewrite (haven't touched it in 2 years), but it should be back up now 😄
